# Generated by Django 2.0.1 on 2018-03-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggyboi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
