# Generated by Django 2.0.1 on 2018-03-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggyboi', '0002_post_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.FloatField(default=0),
        ),
    ]
