# Generated by Django 2.0.1 on 2018-03-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggyboi', '0003_auto_20180322_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field',
            field=models.CharField(default='', max_length=10, verbose_name=('author', 'title', 'text', 'created_date', 'published_date', 'number')),
        ),
    ]
