# Generated by Django 2.0.1 on 2018-03-29 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggyboi', '0005_auto_20180328_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='field',
        ),
    ]
